// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: migratorservice.proto

package migrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MigrationPhase is the lifecycle phase of a migration workflow.
type MigrationPhase int32

const (
	MigrationPhase_MIGRATION_PHASE_UNSPECIFIED        MigrationPhase = 0
	MigrationPhase_MIGRATION_PHASE_CREATED            MigrationPhase = 1
	MigrationPhase_MIGRATION_PHASE_VALIDATING         MigrationPhase = 2
	MigrationPhase_MIGRATION_PHASE_SCHEMA_COPY        MigrationPhase = 3
	MigrationPhase_MIGRATION_PHASE_CREATE_PUBLICATION MigrationPhase = 4
	MigrationPhase_MIGRATION_PHASE_COPYING            MigrationPhase = 5
	MigrationPhase_MIGRATION_PHASE_DROPPED            MigrationPhase = 7
	MigrationPhase_MIGRATION_PHASE_FAILED             MigrationPhase = 8
	MigrationPhase_MIGRATION_PHASE_COMPLETING         MigrationPhase = 10
	// IMPORTING/EXPORTING are the caught-up steady states (importing from / serving
	// and exporting to the external database). SWITCHING_TO_* are the transient
	// cutover (to export) and roll-back (to import).
	MigrationPhase_MIGRATION_PHASE_IMPORTING           MigrationPhase = 11
	MigrationPhase_MIGRATION_PHASE_EXPORTING           MigrationPhase = 12
	MigrationPhase_MIGRATION_PHASE_SWITCHING_TO_IMPORT MigrationPhase = 13
	MigrationPhase_MIGRATION_PHASE_SWITCHING_TO_EXPORT MigrationPhase = 14
)

// Enum value maps for MigrationPhase.
var (
	MigrationPhase_name = map[int32]string{
		0:  "MIGRATION_PHASE_UNSPECIFIED",
		1:  "MIGRATION_PHASE_CREATED",
		2:  "MIGRATION_PHASE_VALIDATING",
		3:  "MIGRATION_PHASE_SCHEMA_COPY",
		4:  "MIGRATION_PHASE_CREATE_PUBLICATION",
		5:  "MIGRATION_PHASE_COPYING",
		7:  "MIGRATION_PHASE_DROPPED",
		8:  "MIGRATION_PHASE_FAILED",
		10: "MIGRATION_PHASE_COMPLETING",
		11: "MIGRATION_PHASE_IMPORTING",
		12: "MIGRATION_PHASE_EXPORTING",
		13: "MIGRATION_PHASE_SWITCHING_TO_IMPORT",
		14: "MIGRATION_PHASE_SWITCHING_TO_EXPORT",
	}
	MigrationPhase_value = map[string]int32{
		"MIGRATION_PHASE_UNSPECIFIED":         0,
		"MIGRATION_PHASE_CREATED":             1,
		"MIGRATION_PHASE_VALIDATING":          2,
		"MIGRATION_PHASE_SCHEMA_COPY":         3,
		"MIGRATION_PHASE_CREATE_PUBLICATION":  4,
		"MIGRATION_PHASE_COPYING":             5,
		"MIGRATION_PHASE_DROPPED":             7,
		"MIGRATION_PHASE_FAILED":              8,
		"MIGRATION_PHASE_COMPLETING":          10,
		"MIGRATION_PHASE_IMPORTING":           11,
		"MIGRATION_PHASE_EXPORTING":           12,
		"MIGRATION_PHASE_SWITCHING_TO_IMPORT": 13,
		"MIGRATION_PHASE_SWITCHING_TO_EXPORT": 14,
	}
)

func (x MigrationPhase) Enum() *MigrationPhase {
	p := new(MigrationPhase)
	*p = x
	return p
}

func (x MigrationPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_migratorservice_proto_enumTypes[0].Descriptor()
}

func (MigrationPhase) Type() protoreflect.EnumType {
	return &file_migratorservice_proto_enumTypes[0]
}

func (x MigrationPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationPhase.Descriptor instead.
func (MigrationPhase) EnumDescriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{0}
}

// MigrationDirection is which side is currently the publisher.
type MigrationDirection int32

const (
	MigrationDirection_MIGRATION_DIRECTION_UNSPECIFIED MigrationDirection = 0
	// IMPORT: the external old database is the source (old DB -> Multigres).
	MigrationDirection_MIGRATION_DIRECTION_IMPORT MigrationDirection = 1
	// EXPORT: Multigres is the source (Multigres -> old DB), for fail-back.
	MigrationDirection_MIGRATION_DIRECTION_EXPORT MigrationDirection = 2
)

// Enum value maps for MigrationDirection.
var (
	MigrationDirection_name = map[int32]string{
		0: "MIGRATION_DIRECTION_UNSPECIFIED",
		1: "MIGRATION_DIRECTION_IMPORT",
		2: "MIGRATION_DIRECTION_EXPORT",
	}
	MigrationDirection_value = map[string]int32{
		"MIGRATION_DIRECTION_UNSPECIFIED": 0,
		"MIGRATION_DIRECTION_IMPORT":      1,
		"MIGRATION_DIRECTION_EXPORT":      2,
	}
)

func (x MigrationDirection) Enum() *MigrationDirection {
	p := new(MigrationDirection)
	*p = x
	return p
}

func (x MigrationDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_migratorservice_proto_enumTypes[1].Descriptor()
}

func (MigrationDirection) Type() protoreflect.EnumType {
	return &file_migratorservice_proto_enumTypes[1]
}

func (x MigrationDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationDirection.Descriptor instead.
func (MigrationDirection) EnumDescriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{1}
}

// TableSpec selects tables for a migration, mirroring one CREATE PUBLICATION
// "FOR TABLE" entry. qualified_name is the list of (optionally qualified) table names.
type TableSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// qualified_name is the schema-qualified table name ("schema.table").
	QualifiedName []string `protobuf:"bytes,1,rep,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSpec) Reset() {
	*x = TableSpec{}
	mi := &file_migratorservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSpec) ProtoMessage() {}

func (x *TableSpec) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSpec.ProtoReflect.Descriptor instead.
func (*TableSpec) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{0}
}

func (x *TableSpec) GetQualifiedName() []string {
	if x != nil {
		return x.QualifiedName
	}
	return nil
}

// SchemaSpec selects tables in a schema rather than tables and matches
// FOR TABLES IN SCHEMA name [, ...] construction.
type SchemaSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        []string               `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaSpec) Reset() {
	*x = SchemaSpec{}
	mi := &file_migratorservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaSpec) ProtoMessage() {}

func (x *SchemaSpec) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaSpec.ProtoReflect.Descriptor instead.
func (*SchemaSpec) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaSpec) GetSchema() []string {
	if x != nil {
		return x.Schema
	}
	return nil
}

// SelectionObject is one entry in a migration's table selection: either a table
// (optionally with per-table clauses, see TableSpec) or a whole schema. Schema
// selection is a SNAPSHOT of the tables owned by the source role in that schema
// at create time — tables added to the schema later are NOT auto-included
// (native dynamic FOR TABLES IN SCHEMA would require superuser on the source).
type SelectionObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Object:
	//
	//	*SelectionObject_Table
	//	*SelectionObject_Schema
	//	*SelectionObject_All
	Object        isSelectionObject_Object `protobuf_oneof:"object"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectionObject) Reset() {
	*x = SelectionObject{}
	mi := &file_migratorservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectionObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionObject) ProtoMessage() {}

func (x *SelectionObject) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionObject.ProtoReflect.Descriptor instead.
func (*SelectionObject) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{2}
}

func (x *SelectionObject) GetObject() isSelectionObject_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SelectionObject) GetTable() *TableSpec {
	if x != nil {
		if x, ok := x.Object.(*SelectionObject_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *SelectionObject) GetSchema() *SchemaSpec {
	if x != nil {
		if x, ok := x.Object.(*SelectionObject_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

func (x *SelectionObject) GetAll() bool {
	if x != nil {
		if x, ok := x.Object.(*SelectionObject_All); ok {
			return x.All
		}
	}
	return false
}

type isSelectionObject_Object interface {
	isSelectionObject_Object()
}

type SelectionObject_Table struct {
	Table *TableSpec `protobuf:"bytes,1,opt,name=table,proto3,oneof"`
}

type SelectionObject_Schema struct {
	Schema *SchemaSpec `protobuf:"bytes,2,opt,name=schema,proto3,oneof"`
}

type SelectionObject_All struct {
	All bool `protobuf:"varint,3,opt,name=all,proto3,oneof"`
}

func (*SelectionObject_Table) isSelectionObject_Object() {}

func (*SelectionObject_Schema) isSelectionObject_Object() {}

func (*SelectionObject_All) isSelectionObject_Object() {}

// Migration is the static, immutable configuration of a migration workflow —
// everything a caller supplies in CreateMigrationRequest. Live state (phase,
// progress, errors) is reported separately by MigrationStatus.
type Migration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the optional, human-friendly identifier, unique per target database.
	// Empty for migrations created without one. The generated id remains the stable
	// internal key.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// source_dsn is a full libpq conninfo to the standalone source postgres (may
	// include TLS options). Returned as-is on read paths, which may expose a
	// password. Intentional for now while this API is only used by trusted
	// operators; revisit (redact or split out) before it is exposed more widely.
	SourceDsn      string           `protobuf:"bytes,3,opt,name=source_dsn,json=sourceDsn,proto3" json:"source_dsn,omitempty"`
	TargetDatabase string           `protobuf:"bytes,4,opt,name=target_database,json=targetDatabase,proto3" json:"target_database,omitempty"`
	TargetShard    string           `protobuf:"bytes,5,opt,name=target_shard,json=targetShard,proto3" json:"target_shard,omitempty"`
	Objects        *SelectionObject `protobuf:"bytes,6,opt,name=objects,proto3" json:"objects,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_migratorservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{3}
}

func (x *Migration) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Migration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Migration) GetSourceDsn() string {
	if x != nil {
		return x.SourceDsn
	}
	return ""
}

func (x *Migration) GetTargetDatabase() string {
	if x != nil {
		return x.TargetDatabase
	}
	return ""
}

func (x *Migration) GetTargetShard() string {
	if x != nil {
		return x.TargetShard
	}
	return ""
}

func (x *Migration) GetObjects() *SelectionObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

// MigrationStatus is the live, observed state of a migration workflow:
// everything that changes after creation. Every RPC that hands back a
// migration returns both it and the migration's static Migration (see
// MigrationInfo).
type MigrationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase MigrationPhase         `protobuf:"varint,2,opt,name=phase,proto3,enum=migrator.MigrationPhase" json:"phase,omitempty"`
	// last_error is the failure reason, set when phase is FAILED.
	LastError string `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// total_relations / ready_relations report initial-copy progress (srsubstate).
	TotalRelations   int64                  `protobuf:"varint,4,opt,name=total_relations,json=totalRelations,proto3" json:"total_relations,omitempty"`
	ReadyRelations   int64                  `protobuf:"varint,5,opt,name=ready_relations,json=readyRelations,proto3" json:"ready_relations,omitempty"`
	CaughtUp         bool                   `protobuf:"varint,6,opt,name=caught_up,json=caughtUp,proto3" json:"caught_up,omitempty"`
	PublicationName  string                 `protobuf:"bytes,7,opt,name=publication_name,json=publicationName,proto3" json:"publication_name,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,8,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// active_direction is which side is currently the publisher.
	ActiveDirection MigrationDirection `protobuf:"varint,10,opt,name=active_direction,json=activeDirection,proto3,enum=migrator.MigrationDirection" json:"active_direction,omitempty"`
	// streaming_since is set when the migration first reaches STREAMING.
	StreamingSince *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=streaming_since,json=streamingSince,proto3" json:"streaming_since,omitempty"`
	// lag_bytes / lag_seconds are the live replication lag measured on the current
	// publisher (the external source in IMPORT, the Multigres target in EXPORT):
	// lag_bytes = pg_current_wal_lsn() - confirmed_flush_lsn, lag_seconds = the
	// walsender's replay_lag. Both are 0 when the migration is not streaming or the
	// lag cannot be read. lag_bytes is the same measure ActivateMigration.max_lag_bytes
	// gates on.
	LagBytes      uint64  `protobuf:"varint,12,opt,name=lag_bytes,json=lagBytes,proto3" json:"lag_bytes,omitempty"`
	LagSeconds    float64 `protobuf:"fixed64,13,opt,name=lag_seconds,json=lagSeconds,proto3" json:"lag_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationStatus) Reset() {
	*x = MigrationStatus{}
	mi := &file_migratorservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStatus) ProtoMessage() {}

func (x *MigrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStatus.ProtoReflect.Descriptor instead.
func (*MigrationStatus) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{4}
}

func (x *MigrationStatus) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MigrationStatus) GetPhase() MigrationPhase {
	if x != nil {
		return x.Phase
	}
	return MigrationPhase_MIGRATION_PHASE_UNSPECIFIED
}

func (x *MigrationStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *MigrationStatus) GetTotalRelations() int64 {
	if x != nil {
		return x.TotalRelations
	}
	return 0
}

func (x *MigrationStatus) GetReadyRelations() int64 {
	if x != nil {
		return x.ReadyRelations
	}
	return 0
}

func (x *MigrationStatus) GetCaughtUp() bool {
	if x != nil {
		return x.CaughtUp
	}
	return false
}

func (x *MigrationStatus) GetPublicationName() string {
	if x != nil {
		return x.PublicationName
	}
	return ""
}

func (x *MigrationStatus) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *MigrationStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MigrationStatus) GetActiveDirection() MigrationDirection {
	if x != nil {
		return x.ActiveDirection
	}
	return MigrationDirection_MIGRATION_DIRECTION_UNSPECIFIED
}

func (x *MigrationStatus) GetStreamingSince() *timestamppb.Timestamp {
	if x != nil {
		return x.StreamingSince
	}
	return nil
}

func (x *MigrationStatus) GetLagBytes() uint64 {
	if x != nil {
		return x.LagBytes
	}
	return 0
}

func (x *MigrationStatus) GetLagSeconds() float64 {
	if x != nil {
		return x.LagSeconds
	}
	return 0
}

// MigrationInfo pairs a migration's static configuration with its live
// status. It is the shape every RPC returns for one migration.
type MigrationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	Status        *MigrationStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationInfo) Reset() {
	*x = MigrationInfo{}
	mi := &file_migratorservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationInfo) ProtoMessage() {}

func (x *MigrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationInfo.ProtoReflect.Descriptor instead.
func (*MigrationInfo) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{5}
}

func (x *MigrationInfo) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *MigrationInfo) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// MigrationJournalEntry is one row of a migration's durable, append-only audit
// log (multigres.migration_journal): each lifecycle action (create, start, phase
// advance, direction switch, drop, failure) appends one entry. It is an internal
// audit surface — never contains credentials — and, unlike the Migration
// projection, is retained after the migration is dropped.
type MigrationJournalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// seq is the database-generated global monotonic audit order.
	Seq         int64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	MigrationId int64 `protobuf:"varint,2,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	// migration_name is the migration's optional name, denormalized at write time
	// so the entry stays readable after the migration row is dropped.
	MigrationName string `protobuf:"bytes,3,opt,name=migration_name,json=migrationName,proto3" json:"migration_name,omitempty"`
	// event is the action: CREATE, START, PHASE, ACTIVATE, DEACTIVATE, DROP, FAILED.
	Event string `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	// phase is the migration phase in effect at (or resulting from) the action.
	Phase MigrationPhase `protobuf:"varint,5,opt,name=phase,proto3,enum=migrator.MigrationPhase" json:"phase,omitempty"`
	// direction is the active replication direction at the action.
	Direction MigrationDirection `protobuf:"varint,6,opt,name=direction,proto3,enum=migrator.MigrationDirection" json:"direction,omitempty"`
	// from_lsn is the drained-to / quiesce LSN on the old writer (direction switch
	// and graceful drop); empty otherwise.
	FromLsn string `protobuf:"bytes,7,opt,name=from_lsn,json=fromLsn,proto3" json:"from_lsn,omitempty"`
	// to_lsn is the start LSN on the new writer (direction switch); empty otherwise.
	ToLsn string `protobuf:"bytes,8,opt,name=to_lsn,json=toLsn,proto3" json:"to_lsn,omitempty"`
	// last_error is the failure reason (FAILED entries).
	LastError string `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// detail is free-form context, e.g. "COPYING->IMPORTING" for a phase advance.
	Detail        string                 `protobuf:"bytes,10,opt,name=detail,proto3" json:"detail,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationJournalEntry) Reset() {
	*x = MigrationJournalEntry{}
	mi := &file_migratorservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationJournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationJournalEntry) ProtoMessage() {}

func (x *MigrationJournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationJournalEntry.ProtoReflect.Descriptor instead.
func (*MigrationJournalEntry) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{6}
}

func (x *MigrationJournalEntry) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MigrationJournalEntry) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *MigrationJournalEntry) GetMigrationName() string {
	if x != nil {
		return x.MigrationName
	}
	return ""
}

func (x *MigrationJournalEntry) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *MigrationJournalEntry) GetPhase() MigrationPhase {
	if x != nil {
		return x.Phase
	}
	return MigrationPhase_MIGRATION_PHASE_UNSPECIFIED
}

func (x *MigrationJournalEntry) GetDirection() MigrationDirection {
	if x != nil {
		return x.Direction
	}
	return MigrationDirection_MIGRATION_DIRECTION_UNSPECIFIED
}

func (x *MigrationJournalEntry) GetFromLsn() string {
	if x != nil {
		return x.FromLsn
	}
	return ""
}

func (x *MigrationJournalEntry) GetToLsn() string {
	if x != nil {
		return x.ToLsn
	}
	return ""
}

func (x *MigrationJournalEntry) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *MigrationJournalEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *MigrationJournalEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetMigrationJournalRequest addresses one migration by id or, when id is empty,
// by name. A dropped migration is addressable only by id (the row that carried
// the name is gone, though its journal entries are retained).
type GetMigrationJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationJournalRequest) Reset() {
	*x = GetMigrationJournalRequest{}
	mi := &file_migratorservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationJournalRequest) ProtoMessage() {}

func (x *GetMigrationJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationJournalRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationJournalRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetMigrationJournalRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMigrationJournalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMigrationJournalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries are the migration's journal entries, oldest first.
	Entries       []*MigrationJournalEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationJournalResponse) Reset() {
	*x = GetMigrationJournalResponse{}
	mi := &file_migratorservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationJournalResponse) ProtoMessage() {}

func (x *GetMigrationJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationJournalResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationJournalResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetMigrationJournalResponse) GetEntries() []*MigrationJournalEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateMigrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is an optional, human-friendly identifier, unique per target database.
	// When set it can address the migration in place of the generated id.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// source_dsn is a full libpq conninfo to the standalone source postgres (may
	// include TLS options). Round-tripped as-is in Migration; see the comment
	// there.
	SourceDsn      string `protobuf:"bytes,2,opt,name=source_dsn,json=sourceDsn,proto3" json:"source_dsn,omitempty"`
	TargetDatabase string `protobuf:"bytes,3,opt,name=target_database,json=targetDatabase,proto3" json:"target_database,omitempty"`
	TargetShard    string `protobuf:"bytes,4,opt,name=target_shard,json=targetShard,proto3" json:"target_shard,omitempty"`
	// sequence_margin is added past each sequence's max at a direction switch.
	SequenceMargin int64 `protobuf:"varint,5,opt,name=sequence_margin,json=sequenceMargin,proto3" json:"sequence_margin,omitempty"`
	// objects is the migration's table selection: a table list, a schema list,
	// or all tables owned by the source role. See SelectionObject.
	Objects *SelectionObject `protobuf:"bytes,6,opt,name=objects,proto3" json:"objects,omitempty"`
	// skip_copy_data skips the initial COPY at subscription setup (the data is
	// assumed to be seeded out-of-band). false (the default) performs the
	// initial COPY.
	SkipCopyData bool `protobuf:"varint,7,opt,name=skip_copy_data,json=skipCopyData,proto3" json:"skip_copy_data,omitempty"`
	// skip_schema_copy skips the pg_dump --schema-only step (target schema exists).
	SkipSchemaCopy bool `protobuf:"varint,8,opt,name=skip_schema_copy,json=skipSchemaCopy,proto3" json:"skip_schema_copy,omitempty"`
	// quiesce_roles are optional application role names on the source whose CONNECT
	// privilege is revoked during the ACTIVATE cutover (and restored on a deactivate
	// rollback or teardown), so they cannot reconnect and write to the source once it
	// becomes a subscriber. The hard quiesce always freezes and terminates existing
	// client backends; naming roles here additionally fences reconnects that would
	// otherwise diverge. Each role must exist on the source and must not be the DSN's
	// own role (validated at create time). Empty leaves the terminate + read-only
	// barrier as the only guard.
	QuiesceRoles  []string `protobuf:"bytes,9,rep,name=quiesce_roles,json=quiesceRoles,proto3" json:"quiesce_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMigrationRequest) Reset() {
	*x = CreateMigrationRequest{}
	mi := &file_migratorservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationRequest) ProtoMessage() {}

func (x *CreateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationRequest.ProtoReflect.Descriptor instead.
func (*CreateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{9}
}

func (x *CreateMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMigrationRequest) GetSourceDsn() string {
	if x != nil {
		return x.SourceDsn
	}
	return ""
}

func (x *CreateMigrationRequest) GetTargetDatabase() string {
	if x != nil {
		return x.TargetDatabase
	}
	return ""
}

func (x *CreateMigrationRequest) GetTargetShard() string {
	if x != nil {
		return x.TargetShard
	}
	return ""
}

func (x *CreateMigrationRequest) GetSequenceMargin() int64 {
	if x != nil {
		return x.SequenceMargin
	}
	return 0
}

func (x *CreateMigrationRequest) GetObjects() *SelectionObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *CreateMigrationRequest) GetSkipCopyData() bool {
	if x != nil {
		return x.SkipCopyData
	}
	return false
}

func (x *CreateMigrationRequest) GetSkipSchemaCopy() bool {
	if x != nil {
		return x.SkipSchemaCopy
	}
	return false
}

func (x *CreateMigrationRequest) GetQuiesceRoles() []string {
	if x != nil {
		return x.QuiesceRoles
	}
	return nil
}

type CreateMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	Status        *MigrationStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMigrationResponse) Reset() {
	*x = CreateMigrationResponse{}
	mi := &file_migratorservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationResponse) ProtoMessage() {}

func (x *CreateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationResponse.ProtoReflect.Descriptor instead.
func (*CreateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *CreateMigrationResponse) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// UpdateMigrationRequest changes mutable fields; only fields named in
// update_mask are applied. Supported paths: source_dsn, sequence_margin, and
// (only while CREATED) tables. The migration is addressed by id or, when id is
// empty, by name.
type UpdateMigrationRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// source_dsn, when in the mask, replaces the source connection (ALTER
	// SUBSCRIPTION ... CONNECTION once the subscription exists). Never returned.
	SourceDsn      string   `protobuf:"bytes,3,opt,name=source_dsn,json=sourceDsn,proto3" json:"source_dsn,omitempty"`
	SequenceMargin int64    `protobuf:"varint,4,opt,name=sequence_margin,json=sequenceMargin,proto3" json:"sequence_margin,omitempty"`
	Tables         []string `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	// name addresses the migration when id is empty (it does not rename it).
	Name          string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMigrationRequest) Reset() {
	*x = UpdateMigrationRequest{}
	mi := &file_migratorservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMigrationRequest) ProtoMessage() {}

func (x *UpdateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMigrationRequest.ProtoReflect.Descriptor instead.
func (*UpdateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMigrationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMigrationRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateMigrationRequest) GetSourceDsn() string {
	if x != nil {
		return x.SourceDsn
	}
	return ""
}

func (x *UpdateMigrationRequest) GetSequenceMargin() int64 {
	if x != nil {
		return x.SequenceMargin
	}
	return 0
}

func (x *UpdateMigrationRequest) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *UpdateMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	Status        *MigrationStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMigrationResponse) Reset() {
	*x = UpdateMigrationResponse{}
	mi := &file_migratorservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMigrationResponse) ProtoMessage() {}

func (x *UpdateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMigrationResponse.ProtoReflect.Descriptor instead.
func (*UpdateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *UpdateMigrationResponse) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ActivateMigrationRequest cuts the migration over to serving: drain to lag zero,
// switch to the EXPORT direction, and start serving. Requires the current
// direction to be IMPORT. Addressed by id or, when id is empty, by name.
type ActivateMigrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// max_lag_bytes is the readiness threshold for the cutover. Before quiescing the
	// source, activation polls the live replication lag (the bytes of source WAL the
	// target has not yet confirmed-consumed) and proceeds only once it is at or below
	// this many bytes, so the residual drain under the read-only barrier completes
	// inside the gateway's failover-buffer window (queries buffered during the cutover
	// are replayed, not refused). 0 uses the server default. Choosing it too large
	// relative to the gateway buffer window risks the buffer overflowing mid-cutover;
	// keeping it small enough is the operator's responsibility (not enforced here).
	MaxLagBytes uint64 `protobuf:"varint,3,opt,name=max_lag_bytes,json=maxLagBytes,proto3" json:"max_lag_bytes,omitempty"`
	// wait_timeout_seconds bounds how long activation blocks waiting for the lag to
	// fall to max_lag_bytes. 0 uses the server default. If the threshold is not
	// reached within the timeout, activation fails with a precondition error and the
	// migration stays in the IMPORT direction (no cutover, no serving change).
	WaitTimeoutSeconds int64 `protobuf:"varint,4,opt,name=wait_timeout_seconds,json=waitTimeoutSeconds,proto3" json:"wait_timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActivateMigrationRequest) Reset() {
	*x = ActivateMigrationRequest{}
	mi := &file_migratorservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateMigrationRequest) ProtoMessage() {}

func (x *ActivateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateMigrationRequest.ProtoReflect.Descriptor instead.
func (*ActivateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{13}
}

func (x *ActivateMigrationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivateMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivateMigrationRequest) GetMaxLagBytes() uint64 {
	if x != nil {
		return x.MaxLagBytes
	}
	return 0
}

func (x *ActivateMigrationRequest) GetWaitTimeoutSeconds() int64 {
	if x != nil {
		return x.WaitTimeoutSeconds
	}
	return 0
}

type ActivateMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	Status        *MigrationStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateMigrationResponse) Reset() {
	*x = ActivateMigrationResponse{}
	mi := &file_migratorservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateMigrationResponse) ProtoMessage() {}

func (x *ActivateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateMigrationResponse.ProtoReflect.Descriptor instead.
func (*ActivateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{14}
}

func (x *ActivateMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *ActivateMigrationResponse) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// DeactivateMigrationRequest rolls the migration back to non-serving: stop
// serving, then switch back to the IMPORT direction. Requires the current
// direction to be EXPORT. Addressed by id or, when id is empty, by name.
type DeactivateMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateMigrationRequest) Reset() {
	*x = DeactivateMigrationRequest{}
	mi := &file_migratorservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateMigrationRequest) ProtoMessage() {}

func (x *DeactivateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateMigrationRequest.ProtoReflect.Descriptor instead.
func (*DeactivateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{15}
}

func (x *DeactivateMigrationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeactivateMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeactivateMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	Status        *MigrationStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateMigrationResponse) Reset() {
	*x = DeactivateMigrationResponse{}
	mi := &file_migratorservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateMigrationResponse) ProtoMessage() {}

func (x *DeactivateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateMigrationResponse.ProtoReflect.Descriptor instead.
func (*DeactivateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{16}
}

func (x *DeactivateMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *DeactivateMigrationResponse) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// StartMigrationRequest is addressed by id or, when id is empty, by name.
type StartMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMigrationRequest) Reset() {
	*x = StartMigrationRequest{}
	mi := &file_migratorservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationRequest) ProtoMessage() {}

func (x *StartMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationRequest.ProtoReflect.Descriptor instead.
func (*StartMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{17}
}

func (x *StartMigrationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StartMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	Status        *MigrationStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMigrationResponse) Reset() {
	*x = StartMigrationResponse{}
	mi := &file_migratorservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationResponse) ProtoMessage() {}

func (x *StartMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationResponse.ProtoReflect.Descriptor instead.
func (*StartMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{18}
}

func (x *StartMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *StartMigrationResponse) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetMigrationsRequest returns one migration when id or name is set, else all.
type GetMigrationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name selects one migration by name when id is empty.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationsRequest) Reset() {
	*x = GetMigrationsRequest{}
	mi := &file_migratorservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationsRequest) ProtoMessage() {}

func (x *GetMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationsRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{19}
}

func (x *GetMigrationsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMigrationsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMigrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migrations    []*MigrationInfo       `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationsResponse) Reset() {
	*x = GetMigrationsResponse{}
	mi := &file_migratorservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationsResponse) ProtoMessage() {}

func (x *GetMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationsResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{20}
}

func (x *GetMigrationsResponse) GetMigrations() []*MigrationInfo {
	if x != nil {
		return x.Migrations
	}
	return nil
}

// DropMigrationRequest is addressed by id or, when id is empty, by name.
type DropMigrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// wait blocks until the migration reaches a completable (caught-up) state,
	// then drains and tears down. Mutually exclusive with force.
	Wait bool `protobuf:"varint,2,opt,name=wait,proto3" json:"wait,omitempty"`
	// wait_timeout_seconds bounds wait (0 = no timeout).
	WaitTimeoutSeconds int64 `protobuf:"varint,3,opt,name=wait_timeout_seconds,json=waitTimeoutSeconds,proto3" json:"wait_timeout_seconds,omitempty"`
	// force skips the drain and tears down from any phase.
	Force bool `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	// name addresses the migration when id is empty.
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropMigrationRequest) Reset() {
	*x = DropMigrationRequest{}
	mi := &file_migratorservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropMigrationRequest) ProtoMessage() {}

func (x *DropMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropMigrationRequest.ProtoReflect.Descriptor instead.
func (*DropMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{21}
}

func (x *DropMigrationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DropMigrationRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

func (x *DropMigrationRequest) GetWaitTimeoutSeconds() int64 {
	if x != nil {
		return x.WaitTimeoutSeconds
	}
	return 0
}

func (x *DropMigrationRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DropMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	Status        *MigrationStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropMigrationResponse) Reset() {
	*x = DropMigrationResponse{}
	mi := &file_migratorservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropMigrationResponse) ProtoMessage() {}

func (x *DropMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migratorservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropMigrationResponse.ProtoReflect.Descriptor instead.
func (*DropMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migratorservice_proto_rawDescGZIP(), []int{22}
}

func (x *DropMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *DropMigrationResponse) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_migratorservice_proto protoreflect.FileDescriptor

const file_migratorservice_proto_rawDesc = "" +
	"\n" +
	"\x15migratorservice.proto\x12\bmigrator\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\tTableSpec\x12%\n" +
	"\x0equalified_name\x18\x01 \x03(\tR\rqualifiedName\"$\n" +
	"\n" +
	"SchemaSpec\x12\x16\n" +
	"\x06schema\x18\x01 \x03(\tR\x06schema\"\x8c\x01\n" +
	"\x0fSelectionObject\x12+\n" +
	"\x05table\x18\x01 \x01(\v2\x13.migrator.TableSpecH\x00R\x05table\x12.\n" +
	"\x06schema\x18\x02 \x01(\v2\x14.migrator.SchemaSpecH\x00R\x06schema\x12\x12\n" +
	"\x03all\x18\x03 \x01(\bH\x00R\x03allB\b\n" +
	"\x06object\"\xcf\x01\n" +
	"\tMigration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"source_dsn\x18\x03 \x01(\tR\tsourceDsn\x12'\n" +
	"\x0ftarget_database\x18\x04 \x01(\tR\x0etargetDatabase\x12!\n" +
	"\ftarget_shard\x18\x05 \x01(\tR\vtargetShard\x123\n" +
	"\aobjects\x18\x06 \x01(\v2\x19.migrator.SelectionObjectR\aobjects\"\xbe\x04\n" +
	"\x0fMigrationStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x18.migrator.MigrationPhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12'\n" +
	"\x0ftotal_relations\x18\x04 \x01(\x03R\x0etotalRelations\x12'\n" +
	"\x0fready_relations\x18\x05 \x01(\x03R\x0ereadyRelations\x12\x1b\n" +
	"\tcaught_up\x18\x06 \x01(\bR\bcaughtUp\x12)\n" +
	"\x10publication_name\x18\a \x01(\tR\x0fpublicationName\x12+\n" +
	"\x11subscription_name\x18\b \x01(\tR\x10subscriptionName\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12G\n" +
	"\x10active_direction\x18\n" +
	" \x01(\x0e2\x1c.migrator.MigrationDirectionR\x0factiveDirection\x12C\n" +
	"\x0fstreaming_since\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0estreamingSince\x12\x1b\n" +
	"\tlag_bytes\x18\f \x01(\x04R\blagBytes\x12\x1f\n" +
	"\vlag_seconds\x18\r \x01(\x01R\n" +
	"lagSeconds\"u\n" +
	"\rMigrationInfo\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.migrator.MigrationR\tmigration\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.migrator.MigrationStatusR\x06status\"\x99\x03\n" +
	"\x15MigrationJournalEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12!\n" +
	"\fmigration_id\x18\x02 \x01(\x03R\vmigrationId\x12%\n" +
	"\x0emigration_name\x18\x03 \x01(\tR\rmigrationName\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12.\n" +
	"\x05phase\x18\x05 \x01(\x0e2\x18.migrator.MigrationPhaseR\x05phase\x12:\n" +
	"\tdirection\x18\x06 \x01(\x0e2\x1c.migrator.MigrationDirectionR\tdirection\x12\x19\n" +
	"\bfrom_lsn\x18\a \x01(\tR\afromLsn\x12\x15\n" +
	"\x06to_lsn\x18\b \x01(\tR\x05toLsn\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12\x16\n" +
	"\x06detail\x18\n" +
	" \x01(\tR\x06detail\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"@\n" +
	"\x1aGetMigrationJournalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"X\n" +
	"\x1bGetMigrationJournalResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.migrator.MigrationJournalEntryR\aentries\"\xea\x02\n" +
	"\x16CreateMigrationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"source_dsn\x18\x02 \x01(\tR\tsourceDsn\x12'\n" +
	"\x0ftarget_database\x18\x03 \x01(\tR\x0etargetDatabase\x12!\n" +
	"\ftarget_shard\x18\x04 \x01(\tR\vtargetShard\x12'\n" +
	"\x0fsequence_margin\x18\x05 \x01(\x03R\x0esequenceMargin\x123\n" +
	"\aobjects\x18\x06 \x01(\v2\x19.migrator.SelectionObjectR\aobjects\x12$\n" +
	"\x0eskip_copy_data\x18\a \x01(\bR\fskipCopyData\x12(\n" +
	"\x10skip_schema_copy\x18\b \x01(\bR\x0eskipSchemaCopy\x12#\n" +
	"\rquiesce_roles\x18\t \x03(\tR\fquiesceRoles\"\x7f\n" +
	"\x17CreateMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.migrator.MigrationR\tmigration\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.migrator.MigrationStatusR\x06status\"\xd9\x01\n" +
	"\x16UpdateMigrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x1d\n" +
	"\n" +
	"source_dsn\x18\x03 \x01(\tR\tsourceDsn\x12'\n" +
	"\x0fsequence_margin\x18\x04 \x01(\x03R\x0esequenceMargin\x12\x16\n" +
	"\x06tables\x18\x05 \x03(\tR\x06tables\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\x7f\n" +
	"\x17UpdateMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.migrator.MigrationR\tmigration\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.migrator.MigrationStatusR\x06status\"\x94\x01\n" +
	"\x18ActivateMigrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rmax_lag_bytes\x18\x03 \x01(\x04R\vmaxLagBytes\x120\n" +
	"\x14wait_timeout_seconds\x18\x04 \x01(\x03R\x12waitTimeoutSeconds\"\x81\x01\n" +
	"\x19ActivateMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.migrator.MigrationR\tmigration\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.migrator.MigrationStatusR\x06status\"@\n" +
	"\x1aDeactivateMigrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x83\x01\n" +
	"\x1bDeactivateMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.migrator.MigrationR\tmigration\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.migrator.MigrationStatusR\x06status\";\n" +
	"\x15StartMigrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"~\n" +
	"\x16StartMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.migrator.MigrationR\tmigration\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.migrator.MigrationStatusR\x06status\":\n" +
	"\x14GetMigrationsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\x15GetMigrationsResponse\x127\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x17.migrator.MigrationInfoR\n" +
	"migrations\"\x96\x01\n" +
	"\x14DropMigrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04wait\x18\x02 \x01(\bR\x04wait\x120\n" +
	"\x14wait_timeout_seconds\x18\x03 \x01(\x03R\x12waitTimeoutSeconds\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"}\n" +
	"\x15DropMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.migrator.MigrationR\tmigration\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.migrator.MigrationStatusR\x06status*\xff\x03\n" +
	"\x0eMigrationPhase\x12\x1f\n" +
	"\x1bMIGRATION_PHASE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MIGRATION_PHASE_CREATED\x10\x01\x12\x1e\n" +
	"\x1aMIGRATION_PHASE_VALIDATING\x10\x02\x12\x1f\n" +
	"\x1bMIGRATION_PHASE_SCHEMA_COPY\x10\x03\x12&\n" +
	"\"MIGRATION_PHASE_CREATE_PUBLICATION\x10\x04\x12\x1b\n" +
	"\x17MIGRATION_PHASE_COPYING\x10\x05\x12\x1b\n" +
	"\x17MIGRATION_PHASE_DROPPED\x10\a\x12\x1a\n" +
	"\x16MIGRATION_PHASE_FAILED\x10\b\x12\x1e\n" +
	"\x1aMIGRATION_PHASE_COMPLETING\x10\n" +
	"\x12\x1d\n" +
	"\x19MIGRATION_PHASE_IMPORTING\x10\v\x12\x1d\n" +
	"\x19MIGRATION_PHASE_EXPORTING\x10\f\x12'\n" +
	"#MIGRATION_PHASE_SWITCHING_TO_IMPORT\x10\r\x12'\n" +
	"#MIGRATION_PHASE_SWITCHING_TO_EXPORT\x10\x0e\"\x04\b\x06\x10\x06\"\x04\b\t\x10\t*\x19MIGRATION_PHASE_STREAMING*\x19MIGRATION_PHASE_SWITCHING*y\n" +
	"\x12MigrationDirection\x12#\n" +
	"\x1fMIGRATION_DIRECTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMIGRATION_DIRECTION_IMPORT\x10\x01\x12\x1e\n" +
	"\x1aMIGRATION_DIRECTION_EXPORT\x10\x022\xd9\x05\n" +
	"\bMigrator\x12V\n" +
	"\x0fCreateMigration\x12 .migrator.CreateMigrationRequest\x1a!.migrator.CreateMigrationResponse\x12S\n" +
	"\x0eStartMigration\x12\x1f.migrator.StartMigrationRequest\x1a .migrator.StartMigrationResponse\x12V\n" +
	"\x0fUpdateMigration\x12 .migrator.UpdateMigrationRequest\x1a!.migrator.UpdateMigrationResponse\x12P\n" +
	"\rGetMigrations\x12\x1e.migrator.GetMigrationsRequest\x1a\x1f.migrator.GetMigrationsResponse\x12b\n" +
	"\x13GetMigrationJournal\x12$.migrator.GetMigrationJournalRequest\x1a%.migrator.GetMigrationJournalResponse\x12\\\n" +
	"\x11ActivateMigration\x12\".migrator.ActivateMigrationRequest\x1a#.migrator.ActivateMigrationResponse\x12b\n" +
	"\x13DeactivateMigration\x12$.migrator.DeactivateMigrationRequest\x1a%.migrator.DeactivateMigrationResponse\x12P\n" +
	"\rDropMigration\x12\x1e.migrator.DropMigrationRequest\x1a\x1f.migrator.DropMigrationResponseB/Z-github.com/multigres/multigres/go/pb/migratorb\x06proto3"

var (
	file_migratorservice_proto_rawDescOnce sync.Once
	file_migratorservice_proto_rawDescData []byte
)

func file_migratorservice_proto_rawDescGZIP() []byte {
	file_migratorservice_proto_rawDescOnce.Do(func() {
		file_migratorservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migratorservice_proto_rawDesc), len(file_migratorservice_proto_rawDesc)))
	})
	return file_migratorservice_proto_rawDescData
}

var file_migratorservice_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_migratorservice_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_migratorservice_proto_goTypes = []any{
	(MigrationPhase)(0),                 // 0: migrator.MigrationPhase
	(MigrationDirection)(0),             // 1: migrator.MigrationDirection
	(*TableSpec)(nil),                   // 2: migrator.TableSpec
	(*SchemaSpec)(nil),                  // 3: migrator.SchemaSpec
	(*SelectionObject)(nil),             // 4: migrator.SelectionObject
	(*Migration)(nil),                   // 5: migrator.Migration
	(*MigrationStatus)(nil),             // 6: migrator.MigrationStatus
	(*MigrationInfo)(nil),               // 7: migrator.MigrationInfo
	(*MigrationJournalEntry)(nil),       // 8: migrator.MigrationJournalEntry
	(*GetMigrationJournalRequest)(nil),  // 9: migrator.GetMigrationJournalRequest
	(*GetMigrationJournalResponse)(nil), // 10: migrator.GetMigrationJournalResponse
	(*CreateMigrationRequest)(nil),      // 11: migrator.CreateMigrationRequest
	(*CreateMigrationResponse)(nil),     // 12: migrator.CreateMigrationResponse
	(*UpdateMigrationRequest)(nil),      // 13: migrator.UpdateMigrationRequest
	(*UpdateMigrationResponse)(nil),     // 14: migrator.UpdateMigrationResponse
	(*ActivateMigrationRequest)(nil),    // 15: migrator.ActivateMigrationRequest
	(*ActivateMigrationResponse)(nil),   // 16: migrator.ActivateMigrationResponse
	(*DeactivateMigrationRequest)(nil),  // 17: migrator.DeactivateMigrationRequest
	(*DeactivateMigrationResponse)(nil), // 18: migrator.DeactivateMigrationResponse
	(*StartMigrationRequest)(nil),       // 19: migrator.StartMigrationRequest
	(*StartMigrationResponse)(nil),      // 20: migrator.StartMigrationResponse
	(*GetMigrationsRequest)(nil),        // 21: migrator.GetMigrationsRequest
	(*GetMigrationsResponse)(nil),       // 22: migrator.GetMigrationsResponse
	(*DropMigrationRequest)(nil),        // 23: migrator.DropMigrationRequest
	(*DropMigrationResponse)(nil),       // 24: migrator.DropMigrationResponse
	(*timestamppb.Timestamp)(nil),       // 25: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),       // 26: google.protobuf.FieldMask
}
var file_migratorservice_proto_depIdxs = []int32{
	2,  // 0: migrator.SelectionObject.table:type_name -> migrator.TableSpec
	3,  // 1: migrator.SelectionObject.schema:type_name -> migrator.SchemaSpec
	4,  // 2: migrator.Migration.objects:type_name -> migrator.SelectionObject
	0,  // 3: migrator.MigrationStatus.phase:type_name -> migrator.MigrationPhase
	25, // 4: migrator.MigrationStatus.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: migrator.MigrationStatus.active_direction:type_name -> migrator.MigrationDirection
	25, // 6: migrator.MigrationStatus.streaming_since:type_name -> google.protobuf.Timestamp
	5,  // 7: migrator.MigrationInfo.migration:type_name -> migrator.Migration
	6,  // 8: migrator.MigrationInfo.status:type_name -> migrator.MigrationStatus
	0,  // 9: migrator.MigrationJournalEntry.phase:type_name -> migrator.MigrationPhase
	1,  // 10: migrator.MigrationJournalEntry.direction:type_name -> migrator.MigrationDirection
	25, // 11: migrator.MigrationJournalEntry.created_at:type_name -> google.protobuf.Timestamp
	8,  // 12: migrator.GetMigrationJournalResponse.entries:type_name -> migrator.MigrationJournalEntry
	4,  // 13: migrator.CreateMigrationRequest.objects:type_name -> migrator.SelectionObject
	5,  // 14: migrator.CreateMigrationResponse.migration:type_name -> migrator.Migration
	6,  // 15: migrator.CreateMigrationResponse.status:type_name -> migrator.MigrationStatus
	26, // 16: migrator.UpdateMigrationRequest.update_mask:type_name -> google.protobuf.FieldMask
	5,  // 17: migrator.UpdateMigrationResponse.migration:type_name -> migrator.Migration
	6,  // 18: migrator.UpdateMigrationResponse.status:type_name -> migrator.MigrationStatus
	5,  // 19: migrator.ActivateMigrationResponse.migration:type_name -> migrator.Migration
	6,  // 20: migrator.ActivateMigrationResponse.status:type_name -> migrator.MigrationStatus
	5,  // 21: migrator.DeactivateMigrationResponse.migration:type_name -> migrator.Migration
	6,  // 22: migrator.DeactivateMigrationResponse.status:type_name -> migrator.MigrationStatus
	5,  // 23: migrator.StartMigrationResponse.migration:type_name -> migrator.Migration
	6,  // 24: migrator.StartMigrationResponse.status:type_name -> migrator.MigrationStatus
	7,  // 25: migrator.GetMigrationsResponse.migrations:type_name -> migrator.MigrationInfo
	5,  // 26: migrator.DropMigrationResponse.migration:type_name -> migrator.Migration
	6,  // 27: migrator.DropMigrationResponse.status:type_name -> migrator.MigrationStatus
	11, // 28: migrator.Migrator.CreateMigration:input_type -> migrator.CreateMigrationRequest
	19, // 29: migrator.Migrator.StartMigration:input_type -> migrator.StartMigrationRequest
	13, // 30: migrator.Migrator.UpdateMigration:input_type -> migrator.UpdateMigrationRequest
	21, // 31: migrator.Migrator.GetMigrations:input_type -> migrator.GetMigrationsRequest
	9,  // 32: migrator.Migrator.GetMigrationJournal:input_type -> migrator.GetMigrationJournalRequest
	15, // 33: migrator.Migrator.ActivateMigration:input_type -> migrator.ActivateMigrationRequest
	17, // 34: migrator.Migrator.DeactivateMigration:input_type -> migrator.DeactivateMigrationRequest
	23, // 35: migrator.Migrator.DropMigration:input_type -> migrator.DropMigrationRequest
	12, // 36: migrator.Migrator.CreateMigration:output_type -> migrator.CreateMigrationResponse
	20, // 37: migrator.Migrator.StartMigration:output_type -> migrator.StartMigrationResponse
	14, // 38: migrator.Migrator.UpdateMigration:output_type -> migrator.UpdateMigrationResponse
	22, // 39: migrator.Migrator.GetMigrations:output_type -> migrator.GetMigrationsResponse
	10, // 40: migrator.Migrator.GetMigrationJournal:output_type -> migrator.GetMigrationJournalResponse
	16, // 41: migrator.Migrator.ActivateMigration:output_type -> migrator.ActivateMigrationResponse
	18, // 42: migrator.Migrator.DeactivateMigration:output_type -> migrator.DeactivateMigrationResponse
	24, // 43: migrator.Migrator.DropMigration:output_type -> migrator.DropMigrationResponse
	36, // [36:44] is the sub-list for method output_type
	28, // [28:36] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_migratorservice_proto_init() }
func file_migratorservice_proto_init() {
	if File_migratorservice_proto != nil {
		return
	}
	file_migratorservice_proto_msgTypes[2].OneofWrappers = []any{
		(*SelectionObject_Table)(nil),
		(*SelectionObject_Schema)(nil),
		(*SelectionObject_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migratorservice_proto_rawDesc), len(file_migratorservice_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migratorservice_proto_goTypes,
		DependencyIndexes: file_migratorservice_proto_depIdxs,
		EnumInfos:         file_migratorservice_proto_enumTypes,
		MessageInfos:      file_migratorservice_proto_msgTypes,
	}.Build()
	File_migratorservice_proto = out.File
	file_migratorservice_proto_goTypes = nil
	file_migratorservice_proto_depIdxs = nil
}
